/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * AppointMe.Api | v1
 * OpenAPI spec version: 1.0.0
 */
export type AppointmentStatus = (typeof AppointmentStatus)[keyof typeof AppointmentStatus];

export const AppointmentStatus = {
    Scheduled: 'Scheduled',
    Cancelled: 'Cancelled',
} as const;

export interface AppointmentDto {
    id: string;
    start: string;
    end: string;
    status: AppointmentStatus;
    providerId: string;
    /** @nullable */
    providerFirstName?: string | null;
    /** @nullable */
    providerLastName?: string | null;
    /** @nullable */
    providerName?: string | null;
    /** @nullable */
    providerInitials?: string | null;
    attendeeId: string;
    /** @nullable */
    attendeeFirstName?: string | null;
    /** @nullable */
    attendeeLastName?: string | null;
    /** @nullable */
    attendeeName?: string | null;
    /** @nullable */
    attendeeInitials?: string | null;
    /** @nullable */
    notes?: string | null;
    scheduledAt: string;
}

export interface CompanyMembership {
    companyId: string;
    companyName: string;
    timeZone: string;
}

export type Gender = (typeof Gender)[keyof typeof Gender];

export const Gender = {
    Male: 'Male',
    Female: 'Female',
    Other: 'Other',
} as const;

export interface CustomerDto {
    id: string;
    fullName: string;
    firstName: string;
    /** @nullable */
    lastName?: string | null;
    initials: string;
    /** @nullable */
    dateOfBirth?: string | null;
    gender?: null | Gender;
    /** @nullable */
    email?: string | null;
    registrationDate: string;
}

export interface GetCurrentUserAccessResponse {
    companyId: string;
    roles: string[];
    permissions: string[];
}

export interface GetCurrentUserResponse {
    isAuthenticated: boolean;
    /** @nullable */
    userId?: string | null;
    /** @nullable */
    name?: string | null;
    /** @nullable */
    initials?: string | null;
    /** @nullable */
    email?: string | null;
    hasPendingInvitations?: boolean;
    /** @nullable */
    companies?: CompanyMembership[] | null;
    hasMembership?: boolean;
}

export interface PagedResultOfCustomerDto {
    items: CustomerDto[];
    totalPages?: number;
    totalCount: number;
    page: number;
    limit: number;
}

export interface GetCustomersResponse {
    customers: PagedResultOfCustomerDto;
}

export type Role = (typeof Role)[keyof typeof Role];

export const Role = {
    Owner: 'Owner',
    Manager: 'Manager',
    Staff: 'Staff',
    Receptionist: 'Receptionist',
} as const;

export interface PendingInvitationDto {
    id: string;
    companyId: string;
    companyName: string;
    roles: Role[];
    expiresAt: string;
}

export interface GetPendingInvitationsResponse {
    invitations: PendingInvitationDto[];
}

export interface RoleDefinitionDto {
    role: Role;
    allowsPermissionOverrides: boolean;
}

export interface PermissionGrantDto {
    isGranted: boolean;
    isOverridden: boolean;
}

export type PermissionDtoGrants = { [key: string]: PermissionGrantDto };

export interface PermissionDto {
    key: string;
    grants: PermissionDtoGrants;
}

export interface PermissionGroupDto {
    name: string;
    permissions: PermissionDto[];
}

export interface GetPermissionsResponse {
    roles: RoleDefinitionDto[];
    groups: PermissionGroupDto[];
}

export type TeamMemberType = (typeof TeamMemberType)[keyof typeof TeamMemberType];

export const TeamMemberType = {
    Employee: 'Employee',
    Invitation: 'Invitation',
} as const;

export interface TeamMemberDto {
    id: string;
    /** @nullable */
    fullName?: string | null;
    /** @nullable */
    firstName?: string | null;
    /** @nullable */
    lastName?: string | null;
    /** @nullable */
    initials?: string | null;
    email: string;
    roles: Role[];
    type: TeamMemberType;
    registrationDate: string;
    /** @nullable */
    userId?: string | null;
    isCurrentUser?: boolean;
    isPrimaryOwner?: boolean;
    lockedRoles?: Role[];
}

export interface PagedResultOfTeamMemberDto {
    items: TeamMemberDto[];
    totalPages?: number;
    totalCount: number;
    page: number;
    limit: number;
}

export interface GetTeamResponse {
    members: PagedResultOfTeamMemberDto;
}

export interface InviteEmployeeRequest {
    email: string;
    roles: Role[];
}

export interface InviteEmployeeResponse {
    id: string;
}

export interface OnboardingRequest {
    companyName: string;
    timeZone: string;
}

export interface OnboardingResponse {
    id: string;
}

export type Permission = (typeof Permission)[keyof typeof Permission];

export const Permission = {
    'permissions:view': 'permissions:view',
    'permissions:manage': 'permissions:manage',
    'invitations:resend': 'invitations:resend',
    'invitations:cancel': 'invitations:cancel',
    'employees:view': 'employees:view',
    'employees:invite': 'employees:invite',
    'employees:remove': 'employees:remove',
    'employees:update_roles': 'employees:update_roles',
    'employees:manage_owners': 'employees:manage_owners',
    'customers:view': 'customers:view',
    'customers:create': 'customers:create',
    'customers:update': 'customers:update',
    'customers:delete': 'customers:delete',
    'appointments:view': 'appointments:view',
    'appointments:schedule': 'appointments:schedule',
    'appointments:reschedule': 'appointments:reschedule',
    'appointments:cancel': 'appointments:cancel',
} as const;

export interface RegisterCustomerRequest {
    firstName: string;
    /** @nullable */
    lastName?: string | null;
    /** @nullable */
    dateOfBirth?: string | null;
    /** @nullable */
    gender?: string | null;
    /** @nullable */
    email?: string | null;
}

export interface RegisterCustomerResponse {
    id: string;
}

export interface RescheduleAppointmentRequest {
    providerId: string;
    start: string;
    end: string;
}

export interface RolePermissionGrantDto {
    permissionKey: string;
    role: Role;
    isGranted: boolean;
}

export interface ScheduleAppointmentRequest {
    providerId: string;
    attendeeId: string;
    start: string;
    end: string;
    /** @nullable */
    notes?: string | null;
}

export interface ScheduleAppointmentResponse {
    id: string;
}

export interface ServiceProviderDto {
    id: string;
    /** @nullable */
    firstName?: string | null;
    /** @nullable */
    lastName?: string | null;
    /** @nullable */
    fullName?: string | null;
}

export interface SignupRequest {
    name: string;
    email: string;
}

export interface UpdateCustomerRequest {
    firstName: string;
    /** @nullable */
    lastName?: string | null;
    /** @nullable */
    dateOfBirth?: string | null;
    /** @nullable */
    gender?: string | null;
    /** @nullable */
    email?: string | null;
}

export interface UpdateEmployeeRolesRequest {
    roles: Role[];
}

export interface UpdatePermissionsRequest {
    grants: RolePermissionGrantDto[];
}

export type LoginParams = {
    provider?: string;
    returnUrl?: string;
};

export type GetTeamParams = {
    search?: string;
    limit: number;
    page: number;
};

export type GetCustomersParams = {
    search?: string;
    limit: number;
    page: number;
};

export type GetAppointmentsParams = {
    From: string;
    To: string;
};
